from samples.exception_2 import string_log


string_log("Ouch!".split())
